/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Subscriber = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  subscribedAt?: string;
};

export type BookingRequest = {
  _id: string;
  _type: "bookingRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  eventType?: string;
  venue?: string;
  city?: string;
  date?: string;
  setLength?: string;
  message?: string;
  submittedAt?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Music = {
  _id: string;
  _type: "music";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "album" | "ep" | "single" | "cover";
  title?: string;
  originalArtist?: string;
  coverArt?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  releaseDate?: string;
  videoUrl?: string;
  note?: string;
  links?: {
    spotify?: string;
    appleMusic?: string;
    bandcamp?: string;
    youtube?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Show = {
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  venueName?: string;
  venueCity?: string;
  venueArea?: string;
  supportAct?: string;
  ticketUrl?: string;
  status?: "onSale" | "soldOut" | "waitlist" | "free" | "fewLeft";
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  socialHandle?: string;
};

export type Band = {
  _id: string;
  _type: "band";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  foundedYear?: number;
  genre?: string;
  hometown?: string;
  stats?: Array<{
    label?: string;
    value?: string;
    _type: "stat";
    _key: string;
  }>;
  socialLinks?: {
    instagram?: string;
    tiktok?: string;
    youtube?: string;
    spotify?: string;
    appleMusic?: string;
    bandcamp?: string;
  };
};

export type Theme = {
  _id: string;
  _type: "theme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    primary?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    mark?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  colors?: {
    primary?: Color;
    accent?: Color;
    background?: Color;
    foreground?: Color;
  };
  radius?: "sharp" | "subtle" | "rounded";
  density?: "compact" | "normal" | "airy";
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Subscriber
  | BookingRequest
  | Page
  | Slug
  | SanityImageAssetReference
  | Music
  | SanityImageCrop
  | SanityImageHotspot
  | Show
  | Member
  | Band
  | Theme
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: BAND_QUERY
// Query: *[_type == "band"][0]{  name,  bio,  foundedYear,  genre,  hometown,  stats,  socialLinks}
export type BAND_QUERY_RESULT = {
  name: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  foundedYear: number | null;
  genre: string | null;
  hometown: string | null;
  stats: Array<{
    label?: string;
    value?: string;
    _type: "stat";
    _key: string;
  }> | null;
  socialLinks: {
    instagram?: string;
    tiktok?: string;
    youtube?: string;
    spotify?: string;
    appleMusic?: string;
    bandcamp?: string;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: THEME_QUERY
// Query: *[_type == "theme"][0]{  logo,  colors,  radius,  density}
export type THEME_QUERY_RESULT = {
  logo: {
    primary?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    mark?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
  colors: {
    primary?: Color;
    accent?: Color;
    background?: Color;
    foreground?: Color;
  } | null;
  radius: "rounded" | "sharp" | "subtle" | null;
  density: "airy" | "compact" | "normal" | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: MEMBERS_QUERY
// Query: *[_type == "member"]|order(name asc){  _id,  name,  role,  photo,  bio,  socialHandle}
export type MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  socialHandle: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: SHOWS_QUERY
// Query: *[_type == "show"]|order(date asc){  _id,  date,  venueName,  venueCity,  venueArea,  supportAct,  ticketUrl,  status}
export type SHOWS_QUERY_RESULT = Array<{
  _id: string;
  date: string | null;
  venueName: string | null;
  venueCity: string | null;
  venueArea: string | null;
  supportAct: string | null;
  ticketUrl: string | null;
  status: "fewLeft" | "free" | "onSale" | "soldOut" | "waitlist" | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: RELEASES_QUERY
// Query: *[_type == "music" && kind != "cover"]|order(coalesce(releaseDate, _createdAt) desc){  _id,  kind,  title,  coverArt,  releaseDate,  note,  links}
export type RELEASES_QUERY_RESULT = Array<{
  _id: string;
  kind: "album" | "cover" | "ep" | "single" | null;
  title: string | null;
  coverArt: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  releaseDate: string | null;
  note: string | null;
  links: {
    spotify?: string;
    appleMusic?: string;
    bandcamp?: string;
    youtube?: string;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: COVERS_QUERY
// Query: *[_type == "music" && kind == "cover"]|order(coalesce(releaseDate, _createdAt) desc){  _id,  title,  originalArtist,  coverArt,  videoUrl,  note,  links}
export type COVERS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  originalArtist: string | null;
  coverArt: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  note: string | null;
  links: {
    spotify?: string;
    appleMusic?: string;
    bandcamp?: string;
    youtube?: string;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "band"][0]{\n  name,\n  bio,\n  foundedYear,\n  genre,\n  hometown,\n  stats,\n  socialLinks\n}': BAND_QUERY_RESULT;
    '*[_type == "theme"][0]{\n  logo,\n  colors,\n  radius,\n  density\n}': THEME_QUERY_RESULT;
    '*[_type == "member"]|order(name asc){\n  _id,\n  name,\n  role,\n  photo,\n  bio,\n  socialHandle\n}': MEMBERS_QUERY_RESULT;
    '*[_type == "show"]|order(date asc){\n  _id,\n  date,\n  venueName,\n  venueCity,\n  venueArea,\n  supportAct,\n  ticketUrl,\n  status\n}': SHOWS_QUERY_RESULT;
    '*[_type == "music" && kind != "cover"]|order(coalesce(releaseDate, _createdAt) desc){\n  _id,\n  kind,\n  title,\n  coverArt,\n  releaseDate,\n  note,\n  links\n}': RELEASES_QUERY_RESULT;
    '*[_type == "music" && kind == "cover"]|order(coalesce(releaseDate, _createdAt) desc){\n  _id,\n  title,\n  originalArtist,\n  coverArt,\n  videoUrl,\n  note,\n  links\n}': COVERS_QUERY_RESULT;
  }
}
